coverage:

  parsers:
    javascript:
      enable_partials: yes

    gcov:
      branch_detection:
        conditional: yes
        loop: yes
        method: no
        macro: no

  status:
    project:
      default:
        target: "50%"
    patch:
      enabled: false
